"""Research agent implementation."""

from llm.gemini_client import GeminiClient


class ResearchAgent:
    """Agent responsible for researching a given topic."""

    def __init__(self) -> None:
        """Initialize the research agent."""
        self.llm = GeminiClient()

    def research(self, topic: str) -> str:
        """Research a topic and return structured notes.

        Args:
            topic: Topic to research.

        Returns:
            Research notes generated by Gemini.
        """
        prompt = f"""
        You are an expert research assistant.

        Research the following topic:

        {topic}

        Provide:
        1. Overview
        2. Key Concepts
        3. Recent Developments
        4. Challenges
        5. References to explore
        """

        return self.llm.generate(prompt)